### ISSUE TITLE
NameError: name 'a' is not defined

### ISSUE THREAD

**Issue by tscofield** [tscofield/search.hrdy.index#1]
When running the code I get the following error message

$ python ./bing.py 
hello, welcome to search.hrdy.index
enter the first letter of the latin word below
a
Traceback (most recent call last):
  File "./bing.py", line 3, in <module>
    search = input ()
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined
$

**Comment by tscofield** [comment]
Using python 3 resolves this issue
https://stackoverflow.com/questions/4915361/whats-the-difference-between-raw-input-and-input-in-python3-x
